// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/rson9/limit-rate/internal/config"
	"github.com/rson9/limit-rate/internal/limiter"
)

// Injectors from wire.go:

func InitLimiter() (limiter.Limter, error) {
	limiterConfig, err := config.LoadLimiterConfig()
	if err != nil {
		return nil, err
	}
	limter, err := limiter.NewLimiter(limiterConfig)
	if err != nil {
		return nil, err
	}
	return limter, nil
}
